application/config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  root 'site#home'
  get 'backoffice', to: 'backoffice#home'
  get 'search', to: 'search#ads'
  get 'ads/index'
  get 'profile/dashboard'
  resources :ads, only: [:edit, :update, :new, :create]
  resources :ad_detail, only: [:show]
  resources :categories, only: [:show]
  resources :comments, only: [:create]
  resources :profile_my_data, only: [:edit, :update]
  
  namespace :backoffice do
    get 'admins/index'
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: [:show]
    resources :admins, except: [:show]
    resources :diagrams, only: [:index]
  end
  
  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers: { 
    sessions: 'members/sessions',
    registrations: 'members/registrations'
   }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

application/app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :member
  belongs_to :category, counter_cache: true
  has_many :comments

  #validates
  validates :title, :description, :category, :price, :finish_date, presence: true

  has_attached_file :picture, styles: {large: "800x300#", medium: "320x150#", thumb: "100x100>"}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
  

  scope :descending_order, -> (page) { order(created_at: :desc ).page(page).per(6) }
  scope :search, -> (term, page) { where("lower(title) LIKE ?", "%#{term.downcase}%").page(page).per(6) }
  scope :by_category, ->(id, page) { where(category: id).page(page).per(6) }
  #gem money-rails
  monetize :price_cents
end

application/app/models/adm.rb
class Adm < ApplicationRecord
  belongs_to :member
  belongs_to :category
end

application/app/models/admin.rb
class Admin < ActiveRecord::Base

  #Constante
  enum role: {:full_access => 0, :restricted_access => 1}
  scope :with_full_access, -> { where(role: 0) }
  scope :with_restricted_access, -> { where(role: 1) }

  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

application/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

application/app/models/category.rb
class Category < ApplicationRecord

    #gem FriendlyId
    include FriendlyId
    friendly_id :description, use: :slugged

    has_many :ads

    validates_presence_of :description

    scope :order_by_description, -> { order(:description) }
end

application/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :member
  belongs_to :ad
end

application/app/models/member.rb
class Member < ApplicationRecord
  # Ratyrate gem
  ratyrate_rater

  has_many :ads
  has_one :profile_member
  accepts_nested_attributes_for :profile_member

  #validation
  validate :nested_attributes

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def nested_attributes
    if nested_attributes_blank?
      errors.add(:base, "Preencha os campos Nome e Sobrenome")
    end
  end
  
  def nested_attributes_blank?
    profile_member.first_name.blank? || profile_member.second_name.blank?
  end

end

application/app/models/profile_member.rb
class ProfileMember < ApplicationRecord
    belongs_to :member

    def full_name
        "#{self.first_name} #{self.second_name}"
    end
end

application/app/controllers/ads_controller.rb
class AdsController < ProfileController
  before_action :set_ad, only: [:edit, :update]
  def index
    @ads = Ad.where(member_id: current_member.id)
  end

  def edit
    # set ad via before action (second line of this code)
  end

  def update
    if @ad.update(params_ad)
      redirect_to ads_index_path, notice: "Anúncio atualizado com sucesso!"
    else
      render :edit
    end
  end

  def new
    @ad = Ad.new
  end

  def create
    @ad = Ad.new(params_ad)
    @ad.member = current_member
    if @ad.save
      redirect_to ads_index_path, notice: "Anúncio cadastrado com sucesso!"
    else
      render :new
    end
  end

  private

  def set_ad
    @ad = Ad.find(params[:id])
  end

  def params_ad
    params.require(:ad).permit(:id, :title, :category_id, :price, :description, :picture, :finish_date)
  end
end

application/app/controllers/search_controller.rb
class SearchController < SiteController
    def ads
        @ads = Ad.search(params[:q], params[:page])
        @categories = Category.all
    end
end

application/app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout 'site'
  def home
    @categories = Category.order_by_description
    @ads = Ad.descending_order(6)
    @carousel = Ad.limit(3).order("RANDOM()")
  end
end

application/app/helpers/ad_detail_helper.rb
module AdDetailHelper
end

application/app/helpers/ads_helper.rb
module AdsHelper
end

application/app/helpers/application_helper.rb
module ApplicationHelper
end

application/app/helpers/backoffice_helper.rb
module BackofficeHelper
end

application/app/helpers/categories_helper.rb
module CategoriesHelper
end

application/app/helpers/comments_helper.rb
module CommentsHelper
end

application/app/helpers/profile_helper.rb
module ProfileHelper
end

application/app/helpers/search_helper.rb
module SearchHelper
end

application/app/helpers/site_helper.rb
module SiteHelper
end

application/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

application/app/views/layouts/backoffice.html.erb
<!DOCTYPE html>
<html lang="PT-BR">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Backoffice</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag    'backoffice', media: 'all' %>
  <%= javascript_include_tag 'backoffice' %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
  <body>
      <%= render partial: "layouts/shared_back/navigation" %>
              <!-- Page Content -->
              <div id="page-wrapper">
                  <div class="container-fluid">
                      <div class="row">
                          <div class="col-lg-12">
                              <%= yield %>
                          </div>
                          <!-- /.col-lg-12 -->
                      </div>
                      <!-- /.row -->
                  </div>
                  <!-- /.container-fluid -->
              </div>
              <!-- /#page-wrapper -->
          </div>
          <%= render partial: "layouts/shared_notice/notifications" %>
      
  </body>
</html>

application/app/views/layouts/profile.html.erb
<!DOCTYPE html>
<html lang="PT-BR">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Site</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    'profile', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'profile', 'data-turbolinks-track': 'reload' %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
  <body>
      <%= render partial: "layouts/shared/header" %>

      <div id="wrapper" style="padding-top: 50px;">
                    <!-- Sidebar -->
                    <div id="sidebar-wrapper">
                        <ul class="sidebar-nav">
                            <li class="sidebar-brand">
                                <a href="#">
                                    Perfil
                                </a>
                            </li>
                            <li>
                                <%= link_to  "Dashboard", profile_dashboard_path %>
                            </li>
                            <li>
                                <%= link_to  "Anúncios", ads_index_path %>
                            </li>
                            <li>
                                <%= link_to  "Novo anúncio", new_ad_path %>
                            </li>
                            <li>
                                <%= link_to  "Meus dados", edit_profile_my_datum_path(current_member.id) %>
                            </li>
                            
                        </ul>
                    </div>

                    <div id="page-content-wrapper">
                        
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-lg-12">
                                    <%= yield %>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /#page-content-wrapper -->
                </div>

            <%= render partial: "layouts/shared_notice/notifications" %>
  </body>
</html>

application/app/views/layouts/shared_back/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Rinaldi Ecommerce</a>
        </div>
        <!-- /.navbar-header -->
        <ul class="nav navbar-top-links navbar-right navbar-collapse">
        <li class="text-success"><%= current_admin.email %> </li>
        <li><%= link_to destroy_admin_session_path, method: :delete do %>
            <i class="fa fa-sign-out fa-fw"></i>
            Sair
        <% end %>
        </li>
        </ul>

        <div class="sidebar" role="navigation">
            <ul class="nav sidebar-nav navbar-collapse">
                <li>
                    <%= link_to backoffice_path do %>
                        <i class="fa fa-dashboard fa-fw"></i>Painel
                    <% end %>
                </li>
                <li>
                    <%= link_to backoffice_categories_path do %>
                        <i class="fa fa-th-list fa-fw"></i>Categorias
                    <% end %>
                </li>
                <li>
                    <%= link_to backoffice_admins_index_path do %>
                        <i class="fa fa-users fa-fw"></i>Administradores
                    <% end %>
                </li>
                <% if Rails.env.development? %>
                <li>
                    <%= link_to backoffice_diagrams_path do %>
                        <i class="fa fa-database fa-fw"></i>Diagrama ER
                    <% end %>
                </li>
                <% end %>
            </ul>
        </div>
        <!-- /.sidebar-collapse -->
        <!-- /.navbar-static-side -->
        </nav>

application/app/views/layouts/shared_notice/_notifications.html.erb
<% if notice %>
    <%= javascript_tag "$.notify({ message: '#{notice}'}, {type: 'success', placement: {from: 'top', align: 'center'}});" %>
<% end %>

<% if alert %>
    <%= javascript_tag "$.notify({ message: '#{alert}'}, {type: 'danger', placement: {from: 'top', align: 'center'}});" %>
<% end %>

application/app/views/layouts/site.html.erb
<!DOCTYPE html>
<html lang="PT-BR">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Site</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    'site', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'site', 'data-turbolinks-track': 'reload' %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
  <body>
      <div id="global-spin" class="loading" style="display: none;">Loading&#8230;</div>
      
      <%= render partial: "layouts/shared/header" %>
      <%= yield %>
      <%= render partial: "layouts/shared/footer" %>
      
      <%= render partial: "layouts/shared_notice/notifications" %>
  </body>
</html>