application/config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  root 'site#home'
  get 'backoffice', to: 'backoffice#home'
  get 'search', to: 'search#ads'
  get 'ads/index'
  get 'profile/dashboard'
  resources :ads, only: [:edit, :update, :new, :create]
  resources :ad_detail, only: [:show]
  resources :categories, only: [:show]
  resources :comments, only: [:create]
  resources :profile_my_data, only: [:edit, :update]
  
  namespace :backoffice do
    get 'admins/index'
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: [:show]
    resources :admins, except: [:show]
    resources :diagrams, only: [:index]
  end
  
  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers: { 
    sessions: 'members/sessions',
    registrations: 'members/registrations'
   }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

application/app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :member
  belongs_to :category, counter_cache: true
  has_many :comments

  #validates
  validates :title, :description, :category, :price, :finish_date, presence: true

  has_attached_file :picture, styles: {large: "800x300#", medium: "320x150#", thumb: "100x100>"}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
  

  scope :descending_order, -> (page) { order(created_at: :desc ).page(page).per(6) }
  scope :search, -> (term, page) { where("lower(title) LIKE ?", "%#{term.downcase}%").page(page).per(6) }
  scope :by_category, ->(id, page) { where(category: id).page(page).per(6) }
  #gem money-rails
  monetize :price_cents
end

application/app/models/adm.rb
class Adm < ApplicationRecord
  belongs_to :member
  belongs_to :category
end

application/app/models/admin.rb
class Admin < ActiveRecord::Base

  #Constante
  enum role: {:full_access => 0, :restricted_access => 1}
  scope :with_full_access, -> { where(role: 0) }
  scope :with_restricted_access, -> { where(role: 1) }

  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

application/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

application/app/models/category.rb
class Category < ApplicationRecord

    #gem FriendlyId
    include FriendlyId
    friendly_id :description, use: :slugged

    has_many :ads

    validates_presence_of :description

    scope :order_by_description, -> { order(:description) }
end

application/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :member
  belongs_to :ad
end

application/app/models/member.rb
class Member < ApplicationRecord
  # Ratyrate gem
  ratyrate_rater

  has_many :ads
  has_one :profile_member
  accepts_nested_attributes_for :profile_member

  #validation
  validate :nested_attributes

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def nested_attributes
    if nested_attributes_blank?
      errors.add(:base, "Preencha os campos Nome e Sobrenome")
    end
  end
  
  def nested_attributes_blank?
    profile_member.first_name.blank? || profile_member.second_name.blank?
  end

end

application/app/models/profile_member.rb
class ProfileMember < ApplicationRecord
    belongs_to :member

    def full_name
        "#{self.first_name} #{self.second_name}"
    end
end

application/app/controllers/ads_controller.rb
class AdsController < ProfileController
  before_action :set_ad, only: [:edit, :update]
  def index
    @ads = Ad.where(member_id: current_member.id)
  end

  def edit
    # set ad via before action (second line of this code)
  end

  def update
    if @ad.update(params_ad)
      redirect_to ads_index_path, notice: "Anúncio atualizado com sucesso!"
    else
      render :edit
    end
  end

  def new
    @ad = Ad.new
  end

  def create
    @ad = Ad.new(params_ad)
    @ad.member = current_member
    if @ad.save
      redirect_to ads_index_path, notice: "Anúncio cadastrado com sucesso!"
    else
      render :new
    end
  end

  private

  def set_ad
    @ad = Ad.find(params[:id])
  end

  def params_ad
    params.require(:ad).permit(:id, :title, :category_id, :price, :description, :picture, :finish_date)
  end
end

application/app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  layout "profile"
  def dashboard
  end
end

application/app/controllers/search_controller.rb
class SearchController < SiteController
    def ads
        @ads = Ad.search(params[:q], params[:page])
        @categories = Category.all
    end
end

application/app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout 'site'
  def home
    @categories = Category.order_by_description
    @ads = Ad.descending_order(6)
    @carousel = Ad.limit(3).order("RANDOM()")
  end
end

application/app/helpers/ad_detail_helper.rb
module AdDetailHelper
end

application/app/helpers/ads_helper.rb
module AdsHelper
end

application/app/helpers/application_helper.rb
module ApplicationHelper
end

application/app/helpers/backoffice_helper.rb
module BackofficeHelper
end

application/app/helpers/categories_helper.rb
module CategoriesHelper
end

application/app/helpers/comments_helper.rb
module CommentsHelper
end

application/app/helpers/profile_helper.rb
module ProfileHelper
end

application/app/helpers/profile_my_data_helper.rb
module ProfileMyDataHelper
end

application/app/helpers/search_helper.rb
module SearchHelper
end

application/app/helpers/site/categories_helper.rb
module Site::CategoriesHelper
end

application/app/helpers/site_helper.rb
module SiteHelper
end

application/app/views/site/home.html.erb
<div class="container">
  <div class="row">

      <%= render partial: "site/shared/sidebar" %>
      <%= render partial: "site/shared/search_bar" %>

      <div id="home-detail" class="col-md-9">

         <%= render partial: "site/shared/carousel" %>

          <div class="row">
              
            <%= render partial: "site/shared/ads" %>


          </div>

      </div>

  </div>

</div>

application/app/views/site/shared/_ads.html.erb
<% @ads.each do |ad| %>  
<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <%= image_tag ad.picture.url(:medium) %>
        <div class="caption">
            <h4 class="pull-right"><%= humanized_money_with_symbol ad.price %></h4>
              <%= link_to truncate(ad.title, length: 20), ad_detail_path(ad), remote: true %>
            </h4>
              <p><%= truncate(ad.description, length: 100) %></p>
        </div>
        <div class="ratings">
            <p class="pull-right">15 reviews</p>
            <p>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
            </p>
        </div>
    </div>
</div>
<% end %>

<div class="row">
    <div class="text-center">
        <%= paginate @ads %>
    </div>
</div>

application/app/views/site/shared/_carousel.html.erb
<div class="row carousel-holder">

<div class="col-md-12">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <% @carousel.each do |ad| %>
            <div class="item <%= @carousel.first.id == ad.id ? "active" : "" %>">
                <%= link_to  (image_tag ad.picture.url(:large)), ad_detail_path(ad), remote: true %>
            </div>
            <% end %>
        </div>
        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
    </div>
</div>

</div>

application/app/views/site/shared/_search_bar.html.erb
<%= form_tag search_path, method: :get do %>
<div class="col-lg-9">
    <div class="well well-sm">
       <div class="row">
         <div class="col-lg-3"></div>
         <div class="col-lg-6">
           <div class="input-group">
              <%= text_field_tag(:q, params[:q] ,class:"form-control", placeholder:"Pesquisar por..." ) %>
              <span class="input-group-btn">
               <%= submit_tag("Pesquisar", class: "btn btn-default") %>
              </span>
           </div>
         </div>
       </div>
    </div>
</div>
<% end %>

application/app/views/site/shared/_sidebar.html.erb
<div id="home-sidebar" class="col-md-3">
    <p class="lead">Categorias</p>
    <div class="list-group">
        <% @categories.each do |category| %>
        <%= link_to  "#{category.description} (#{category.ads_count})", category_path(category), class: "list-group-item" %>
        <% end %>
    </div>
</div>