application/config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  root 'site#home'
  get 'backoffice', to: 'backoffice#home'
  get 'search', to: 'search#ads'
  get 'ads/index'
  get 'profile/dashboard'
  resources :ads, only: [:edit, :update, :new, :create]
  resources :ad_detail, only: [:show]
  resources :categories, only: [:show]
  resources :comments, only: [:create]
  resources :profile_my_data, only: [:edit, :update]
  
  namespace :backoffice do
    get 'admins/index'
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: [:show]
    resources :admins, except: [:show]
    resources :diagrams, only: [:index]
  end
  
  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers: { 
    sessions: 'members/sessions',
    registrations: 'members/registrations'
   }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

application/app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :member
  belongs_to :category, counter_cache: true
  has_many :comments

  #validates
  validates :title, :description, :category, :price, :finish_date, presence: true

  has_attached_file :picture, styles: {large: "800x300#", medium: "320x150#", thumb: "100x100>"}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
  

  scope :descending_order, -> (page) { order(created_at: :desc ).page(page).per(6) }
  scope :search, -> (term, page) { where("lower(title) LIKE ?", "%#{term.downcase}%").page(page).per(6) }
  scope :by_category, ->(id, page) { where(category: id).page(page).per(6) }
  #gem money-rails
  monetize :price_cents
end

application/app/models/adm.rb
class Adm < ApplicationRecord
  belongs_to :member
  belongs_to :category
end

application/app/models/admin.rb
class Admin < ActiveRecord::Base

  #Constante
  enum role: {:full_access => 0, :restricted_access => 1}
  scope :with_full_access, -> { where(role: 0) }
  scope :with_restricted_access, -> { where(role: 1) }

  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

application/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

application/app/models/category.rb
class Category < ApplicationRecord

    #gem FriendlyId
    include FriendlyId
    friendly_id :description, use: :slugged

    has_many :ads

    validates_presence_of :description

    scope :order_by_description, -> { order(:description) }
end

application/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :member
  belongs_to :ad
end

application/app/models/member.rb
class Member < ApplicationRecord
  # Ratyrate gem
  ratyrate_rater

  has_many :ads
  has_one :profile_member
  accepts_nested_attributes_for :profile_member

  #validation
  validate :nested_attributes

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def nested_attributes
    if nested_attributes_blank?
      errors.add(:base, "Preencha os campos Nome e Sobrenome")
    end
  end
  
  def nested_attributes_blank?
    profile_member.first_name.blank? || profile_member.second_name.blank?
  end

end

application/app/models/profile_member.rb
class ProfileMember < ApplicationRecord
    belongs_to :member

    def full_name
        "#{self.first_name} #{self.second_name}"
    end
end

application/app/controllers/ad_detail_controller.rb
class AdDetailController < SiteController
    def show
        @categories = Category.order_by_description
        @ad = Ad.find(params[:id])
    end
end

application/app/controllers/ads_controller.rb
class AdsController < ProfileController
  before_action :set_ad, only: [:edit, :update]
  def index
    @ads = Ad.where(member_id: current_member.id)
  end

  def edit
    # set ad via before action (second line of this code)
  end

  def update
    if @ad.update(params_ad)
      redirect_to ads_index_path, notice: "Anúncio atualizado com sucesso!"
    else
      render :edit
    end
  end

  def new
    @ad = Ad.new
  end

  def create
    @ad = Ad.new(params_ad)
    @ad.member = current_member
    if @ad.save
      redirect_to ads_index_path, notice: "Anúncio cadastrado com sucesso!"
    else
      render :new
    end
  end

  private

  def set_ad
    @ad = Ad.find(params[:id])
  end

  def params_ad
    params.require(:ad).permit(:id, :title, :category_id, :price, :description, :picture, :finish_date)
  end
end

application/app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  layout "profile"
  def dashboard
  end
end

application/app/controllers/search_controller.rb
class SearchController < SiteController
    def ads
        @ads = Ad.search(params[:q], params[:page])
        @categories = Category.all
    end
end

application/app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout 'site'
  def home
    @categories = Category.order_by_description
    @ads = Ad.descending_order(6)
    @carousel = Ad.limit(3).order("RANDOM()")
  end
end

application/app/helpers/ad_detail_helper.rb
module AdDetailHelper
end

application/app/helpers/ads_helper.rb
module AdsHelper
end

application/app/helpers/application_helper.rb
module ApplicationHelper
end

application/app/helpers/backoffice_helper.rb
module BackofficeHelper
end

application/app/helpers/categories_helper.rb
module CategoriesHelper
end

application/app/helpers/comments_helper.rb
module CommentsHelper
end

application/app/helpers/profile_helper.rb
module ProfileHelper
end

application/app/helpers/search_helper.rb
module SearchHelper
end

application/app/helpers/site_helper.rb
module SiteHelper
end

application/app/views/ad_detail/_ad.html.erb
<div class="thumbnail">
        <%= image_tag @ad.picture.url(:large), class:"img-responsive" %>
    <div class="caption-full">
        <h4 class="pull-right"><%= humanized_money_with_symbol @ad.price %></h4>
        <h4><a href="#"><%= @ad.title %></a>
        </h4>
        <p><%= @ad.description %></p>
    </div>
    <div class="ratings">
        <p class="pull-right">3 reviews</p>
        <p>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star-empty"></span>
            4.0 stars
        </p>
        
    </div>
</div>

<div class="well">
    <% if member_signed_in? %>
    <div class="text-right">
        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#commentModal">
            Deixe um comentário!
        </button>
    </div>
    <% else %>
    <div class="text-right">
        <button type="button" class="btn btn-success" data-toggle="modal" disabled="disabled" data-target="#commentModal">
            Logue-se para deixar um comentário!
        </button>
    </div>
    <% end %>

    <hr>
    <%= render partial: "ad_detail/comments" %>
    <hr>

</div>


<%= render partial: "ad_detail/modal" %>

application/app/views/ad_detail/_comments.html.erb
<% @ad.comments.each do |comment| %>
<div class="row">
    <div class="col-md-12">
        <span class="glyphicon glyphicon-star"></span>
        <span class="glyphicon glyphicon-star"></span>
        <span class="glyphicon glyphicon-star"></span>
        <span class="glyphicon glyphicon-star"></span>
        <span class="glyphicon glyphicon-star-empty"></span>
        <%= comment.member.email %>
        <span class="pull-right"><%= l comment.created_at %></span>
        <p><%= comment.body %></p>
    </div>
</div>
<% end %>

application/app/views/ad_detail/_modal.html.erb
<%= form_tag comments_path do %>
<div class="modal fade" id="commentModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Deixe seu comentário</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label>Comentário</label>
                    <%= text_area :comment, :body, class: "form-control", rows: 5 %>
                    <%= hidden_field :comment, :ad_id, value: @ad.id %>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    Fechar
                </button>
                <%= submit_tag "Enviar", class: "btn btn-primary" %>
            </div>
        </div>
    </div>
</div>
<% end %>

application/app/views/ad_detail/show.html.erb
<div class="container">
        <div class="row">
      
            <%= render partial: "site/shared/sidebar" %>
            <%= render partial: "site/shared/search_bar" %>
      
            <div id="home-detail" class="col-md-9">
      
               <%= render partial: "site/shared/carousel" %>
      
                <div class="row">
                    
                  <%= render partial: "site/shared/ads" %>
      
      
                </div>
      
            </div>
      
        </div>
      
      </div>

application/app/views/ad_detail/show.js.erb
$('#home-detail').html('<%= j render partial: 'ad_detail/ad' %>');