application/config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  root 'site#home'
  get 'backoffice', to: 'backoffice#home'
  get 'search', to: 'search#ads'
  get 'ads/index'
  get 'profile/dashboard'
  resources :ads, only: [:edit, :update, :new, :create]
  resources :ad_detail, only: [:show]
  resources :categories, only: [:show]
  resources :comments, only: [:create]
  resources :profile_my_data, only: [:edit, :update]
  
  namespace :backoffice do
    get 'admins/index'
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: [:show]
    resources :admins, except: [:show]
    resources :diagrams, only: [:index]
  end
  
  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers: { 
    sessions: 'members/sessions',
    registrations: 'members/registrations'
   }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

application/app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only: [:edit, :update, :destroy]
  def index
      @admin = Admin.all
  end
  
  def new
      @admin = Admin.new
      authorize @admin
  end
  
  def create
      @admin = Admin.new(params_admin)
      if @admin.save
          redirect_to backoffice_admins_path, notice: "O Administrador (#{@admin.email}) foi cadastrado com sucesso"
      else   
          render :new
      end
  end
  
  def edit
  end
  
  def update
    if password_blank?
        params[:admin].delete(:password)
        params[:admin].delete(:password_confirmation)
    end
        
      if @admin.update(params_admin)
        AdminMailer.update_email(current_admin, @admin).deliver_now
        redirect_to backoffice_admins_path, notice: "O Administrador (#{@admin.email}) foi atualizado com sucesso"
      else   
          render :edit
      end
  end

  def password_blank?
    params[:admin][:password].blank? &&
    params[:admin][:password_confirmation].blank?
  end

  def destroy
        if @admin.destroy
            redirect_to backoffice_admins_path, notice: "O Administrador #{@admin.email} foi excluido com sucesso!!!"
        else
            render :index
        end
    end
end

private

def set_admin
    @admin = Admin.find(params[:id])
end

def params_admin
    if @admin.blank?
        params.require(:admin).permit(:name, :email, :role, :password, :password_confirmation)
    else
        params.require(:admin).permit(policy(@admin).permitted_attributes)        
    end
end

application/app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
    before_action :set_category, only: [:edit, :update, :destroy]
def index
    @categories = Category.all
end

def new
    @category = Category.new
end

def create
    @category = CategoryService.create(params_category)
    unless @category.errors.any?
        redirect_to backoffice_categories_path, notice: "A categoria (#{@category.description}) foi cadastrada com sucesso"
    else   
        render :new
    end
end

def edit
end

def update
    if @category.update(params_category)
        redirect_to backoffice_categories_path, notice: "A categoria (#{@category.description}) foi atualizada com sucesso"
    else   
        render :edit
    end
end

def destroy
    if @category.destroy
        redirect_to backoffice_categories_path, notice: "A Categoria #{@category.description} foi removida com sucesso!!!"
    else
        render :index
    end
end
end

private

def set_category
    @category = Category.friendly.find(params[:id])
end

def params_category
    params.require(:category).permit(:description)
end

application/app/controllers/backoffice/categories_controller/category_service.rb
class Backoffice::CategoriesController::CategoryService

    attr_accessor :category

    def self.create(params_category)
        @category = Category.new(params_category)

        if @category.valid?
            @category.save!
        end
        @category
    end
end

application/app/controllers/backoffice/diagrams_controller.rb
class Backoffice::DiagramsController < BackofficeController
    def index
        %x(bundle exec erd --filename='public/diagram')
    end
end

application/app/controllers/backoffice/send_mail_controller.rb
class Backoffice::SendMailController < ApplicationController
    def edit
        @admin = Admin.find(params[:id])
        respond_to do |format|
        format.js
        end
    end

    def create
        begin
            AdminMailer.send_message(current_admin, params[:'recipient-name'], params[:'recipient-subject'], params[:'message-text']).deliver_now            
            @notify_message = "Email enviado com sucesso!"
            @notify_flag = "success"
        rescue
            @notify_message = "Erro ao envar email. Tente novamente!"
            @notify_flag = "error"
        end
        respond_to do |format|
        format.js
        end
    end
end

application/app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
    before_action :authenticate_admin!
    layout "backoffice"

    def index
    end

    def pundit_user
      current_admin
    end
  end

application/app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
    OptionsForRoles = Struct.new(:id, :description)

    def options_for_roles
        Admin.roles_i18n.map do |key, value|
            OptionsForRoles.new(key,value)
        end
    end
end

application/app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

application/app/helpers/backoffice/diagrams_helper.rb
module Backoffice::DiagramsHelper
end

application/app/helpers/backoffice/send_mail_helper.rb
module Backoffice::SendMailHelper
end

application/app/helpers/backoffice_helper.rb
module BackofficeHelper
end

application/app/views/backoffice/admins/edit.html.erb
<%= render partial: "backoffice/admins/shared/form", locals: {action: "Editando Administrador"} %>

application/app/views/backoffice/admins/index.html.erb
<h1 class="page-header">Administradores</h1>

    <div class="panel panel-default">
        <div class="panel-heading">
            Listando Adms
            <%= link_to new_backoffice_admin_path, class: "btn btn-success btn-circle pull-right", style: "margin-top: -5px;" do %> 
            <i class="fa fa-plus"></i>
            <% end %>
        </div>
    <!-- /.panel-heading -->
<div class="panel-body">
<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>Nome</th>
                <th>Email</th>
                <th>Acesso</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <% @admin.each do |admin| %>
            <tr>
                <td><%= admin.id %></td>
                <td><%= admin.name %></td>
                <td><%= admin.email %></td>
                <td><%= admin.role_i18n %></td>
                <td style="width: 115px">
                    <%= link_to edit_backoffice_send_mail_path(admin.id), class: "btn btn-info btn-circle", remote: true do %>
                        <i class="fa fa-envelope"></i>
                    <% end %>
                    <%= link_to edit_backoffice_admin_path(admin.id), class: "btn btn-primary btn-circle" do %>
                        <i class="fa fa-edit"></i>
                    <% end %>
                    <% if current_admin.id != admin.id && policy(@admin).destroy? %>
                    <%= link_to backoffice_admin_path(admin), method: :delete, class:"btn btn-danger btn-circle", data: {confirm: "Tem certeza que quer excluir o ADM #{admin.name}?"}   do %>
                    <i class="fa fa-times"></i>
                    <% end %>
                    <% end %>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

    <!-- /.table-responsive -->
</div>
</div>

<%= render partial: "backoffice/admins/shared/send_mail_modal" %>

application/app/views/backoffice/admins/new.html.erb
<%= render partial: "backoffice/admins/shared/form", locals: {action: "Novo Administrador"} %>